# Generated by Django 3.0.2 on 2020-01-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_pics'),
        ),
    ]
